runtime: python39  # or python38
entrypoint: gunicorn -w 2 -b :$PORT main:app

handlers:
  - url: /static
    static_dir: static

  - url: /.*
    script: auto

automatic_scaling:
  # Configure automatic scaling here
  min_num_instances: 1
  max_num_instances: 2

